spring:
  application:
    name: recording-query-service
  
  # Server Configuration
  server:
    port: 8081
  
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:recording_query
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        
  # Kafka Consumer Configuration
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: recording-query-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      
# Logging Configuration
logging:
  level:
    com.grewmeet.recording: DEBUG
    org.springframework.kafka: INFO
